// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingSystem.API.Data;

#nullable disable

namespace TrainingSystem.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414191908_Fix11")]
    partial class Fix11
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrainingSystem.API.Models.AssessmentResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("RecordTime")
                        .HasColumnType("time");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ResultId")
                        .HasName("PK__Assessme__9769020826C1D63F");

                    b.HasIndex("EnrollmentId");

                    b.ToTable("AssessmentResult", (string)null);
                });

            modelBuilder.Entity("TrainingSystem.API.Models.Certificate", b =>
                {
                    b.Property<int>("CertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificateId"));

                    b.Property<string>("CertificateReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CertificateStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CertificationTrackId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("IssuedDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CertificateId")
                        .HasName("PK__Certific__BBF8A7C16D3CB5E4");

                    b.HasIndex("CertificationTrackId");

                    b.HasIndex("UserId");

                    b.ToTable("Certificate", (string)null);
                });

            modelBuilder.Entity("TrainingSystem.API.Models.CertificationTrack", b =>
                {
                    b.Property<int>("CertificationTrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificationTrackId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CertificationTrackId")
                        .HasName("PK__Certific__E922109781937ECA");

                    b.ToTable("CertificationTrack", (string)null);
                });

            modelBuilder.Entity("TrainingSystem.API.Models.CertificationTrackCourse", b =>
                {
                    b.Property<int>("TrackCourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackCourseId"));

                    b.Property<int>("CertificationTrackId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.HasKey("TrackCourseId")
                        .HasName("PK__Certific__C105F53ABACA6688");

                    b.HasIndex("CertificationTrackId");

                    b.HasIndex("CourseId");

                    b.ToTable("CertificationTrackCourse", (string)null);
                });

            modelBuilder.Entity("TrainingSystem.API.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DefaultCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("DurationHours")
                        .HasColumnType("int");

                    b.Property<decimal>("EnrollmentFee")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("PrerequisiteCourseId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CourseId")
                        .HasName("PK__Course__C92D71A7EAAF5542");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PrerequisiteCourseId");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("TrainingSystem.API.Models.CourseEquipmentRequirement", b =>
                {
                    b.Property<int>("CourseEquipmentRequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseEquipmentRequirementId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityRequired")
                        .HasColumnType("int");

                    b.HasKey("CourseEquipmentRequirementId")
                        .HasName("PK__CourseEq__DC2F3B191FBC31FF");

                    b.HasIndex("CourseId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("CourseEquipmentRequirement", (string)null);
                });

            modelBuilder.Entity("TrainingSystem.API.Models.CourseSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("SessionCapacity")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SessionId")
                        .HasName("PK__CourseSe__C9F492904CDB8DCE");

                    b.HasIndex("CourseId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("CourseSession", (string)null);
                });

            modelBuilder.Entity("TrainingSystem.API.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<DateOnly>("EnrollmentDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsOverdue")
                        .HasColumnType("bit");

                    b.Property<decimal>("OutstandingBalance")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId")
                        .HasName("PK__Enrollme__7F68771BF6E24110");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Enrollment", (string)null);
                });

            modelBuilder.Entity("TrainingSystem.API.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("EquipmentId")
                        .HasName("PK__Equipmen__34474479DE5D2144");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("TrainingSystem.API.Models.ExpertiseArea", b =>
                {
                    b.Property<int>("ExpertiseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpertiseId"));

                    b.Property<string>("ExpertiseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ExpertiseId")
                        .HasName("PK__Expertis__909D2EA1BF9483F3");

                    b.ToTable("ExpertiseArea", (string)null);
                });

            modelBuilder.Entity("TrainingSystem.API.Models.InstructorAvailability", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailabilityId"));

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AvailabilityId")
                        .HasName("PK__Instruct__DA3979B14C90008D");

                    b.HasIndex("UserId");

                    b.ToTable("InstructorAvailability", (string)null);
                });

            modelBuilder.Entity("TrainingSystem.API.Models.InstructorExpertise", b =>
                {
                    b.Property<int>("InstructorExpertiseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorExpertiseId"));

                    b.Property<int>("ExpertiseId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("InstructorExpertiseId")
                        .HasName("PK__Instruct__838966F77FB79AB8");

                    b.HasIndex("ExpertiseId");

                    b.HasIndex("UserId");

                    b.ToTable("InstructorExpertise", (string)null);
                });

            modelBuilder.Entity("TrainingSystem.API.Models.InstructorProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("UserId")
                        .HasName("PK__Instruct__1788CC4CEA6D0CC1");

                    b.ToTable("InstructorProfile", (string)null);
                });

            modelBuilder.Entity("TrainingSystem.API.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E1287BDC95F");

                    b.HasIndex("UserId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("TrainingSystem.API.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PaidDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payment__9B556A38A4C3837F");

                    b.HasIndex("EnrollmentId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("TrainingSystem.API.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE1A2C127234");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("TrainingSystem.API.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoomId")
                        .HasName("PK__Room__32863939F494A3BF");

                    b.ToTable("Room", (string)null);
                });

            modelBuilder.Entity("TrainingSystem.API.Models.RoomEquipment", b =>
                {
                    b.Property<int>("RoomEquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomEquipmentId"));

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("RoomEquipmentId")
                        .HasName("PK__RoomEqui__809194CAB7CD1722");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomEquipment", (string)null);
                });

            modelBuilder.Entity("TrainingSystem.API.Models.SubjectCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("CategoryId")
                        .HasName("PK__SubjectC__19093A0B1BF38FBC");

                    b.ToTable("SubjectCategory", (string)null);
                });

            modelBuilder.Entity("TrainingSystem.API.Models.TraineeCertificationProgress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgressId"));

                    b.Property<int>("CertificationTrackId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EligibleDate")
                        .HasColumnType("date");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProgressId")
                        .HasName("PK__TraineeC__BAE29CA5BB312F9D");

                    b.HasIndex("CertificationTrackId");

                    b.HasIndex("UserId");

                    b.ToTable("TraineeCertificationProgress", (string)null);
                });

            modelBuilder.Entity("TrainingSystem.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CC4C3D214947");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D10534EE24796E")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("TrainingSystem.API.Models.AssessmentResult", b =>
                {
                    b.HasOne("TrainingSystem.API.Models.Enrollment", "Enrollment")
                        .WithMany("AssessmentResults")
                        .HasForeignKey("EnrollmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Assessmen__Enrol__4F7CD00D");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("TrainingSystem.API.Models.Certificate", b =>
                {
                    b.HasOne("TrainingSystem.API.Models.CertificationTrack", "CertificationTrack")
                        .WithMany("Certificates")
                        .HasForeignKey("CertificationTrackId")
                        .IsRequired()
                        .HasConstraintName("FK__Certifica__Certi__5CD6CB2B");

                    b.HasOne("TrainingSystem.API.Models.User", "User")
                        .WithMany("Certificates")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Certifica__UserI__5BE2A6F2");

                    b.Navigation("CertificationTrack");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingSystem.API.Models.CertificationTrackCourse", b =>
                {
                    b.HasOne("TrainingSystem.API.Models.CertificationTrack", "CertificationTrack")
                        .WithMany("CertificationTrackCourses")
                        .HasForeignKey("CertificationTrackId")
                        .IsRequired()
                        .HasConstraintName("FK__Certifica__Certi__5441852A");

                    b.HasOne("TrainingSystem.API.Models.Course", "Course")
                        .WithMany("CertificationTrackCourses")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__Certifica__Cours__5535A963");

                    b.Navigation("CertificationTrack");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("TrainingSystem.API.Models.Course", b =>
                {
                    b.HasOne("TrainingSystem.API.Models.SubjectCategory", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Course__Category__3F466844");

                    b.HasOne("TrainingSystem.API.Models.Course", "PrerequisiteCourse")
                        .WithMany("InversePrerequisiteCourse")
                        .HasForeignKey("PrerequisiteCourseId")
                        .HasConstraintName("FK__Course__Prerequi__403A8C7D");

                    b.Navigation("Category");

                    b.Navigation("PrerequisiteCourse");
                });

            modelBuilder.Entity("TrainingSystem.API.Models.CourseEquipmentRequirement", b =>
                {
                    b.HasOne("TrainingSystem.API.Models.Course", "Course")
                        .WithMany("CourseEquipmentRequirements")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__CourseEqu__Cours__4316F928");

                    b.HasOne("TrainingSystem.API.Models.Equipment", "Equipment")
                        .WithMany("CourseEquipmentRequirements")
                        .HasForeignKey("EquipmentId")
                        .IsRequired()
                        .HasConstraintName("FK__CourseEqu__Equip__440B1D61");

                    b.Navigation("Course");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("TrainingSystem.API.Models.CourseSession", b =>
                {
                    b.HasOne("TrainingSystem.API.Models.Course", "Course")
                        .WithMany("CourseSessions")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__CourseSes__Cours__46E78A0C");

                    b.HasOne("TrainingSystem.API.Models.Room", "Room")
                        .WithMany("CourseSessions")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("FK__CourseSes__RoomI__48CFD27E");

                    b.HasOne("TrainingSystem.API.Models.User", "User")
                        .WithMany("CourseSessions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__CourseSes__UserI__47DBAE45");

                    b.Navigation("Course");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingSystem.API.Models.Enrollment", b =>
                {
                    b.HasOne("TrainingSystem.API.Models.CourseSession", "Session")
                        .WithMany("Enrollments")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("FK__Enrollmen__Sessi__4CA06362");

                    b.HasOne("TrainingSystem.API.Models.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Enrollmen__UserI__4BAC3F29");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingSystem.API.Models.InstructorAvailability", b =>
                {
                    b.HasOne("TrainingSystem.API.Models.User", "User")
                        .WithMany("InstructorAvailabilities")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Instructo__UserI__2D27B809");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingSystem.API.Models.InstructorExpertise", b =>
                {
                    b.HasOne("TrainingSystem.API.Models.ExpertiseArea", "Expertise")
                        .WithMany("InstructorExpertises")
                        .HasForeignKey("ExpertiseId")
                        .IsRequired()
                        .HasConstraintName("FK__Instructo__Exper__31EC6D26");

                    b.HasOne("TrainingSystem.API.Models.User", "User")
                        .WithMany("InstructorExpertises")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Instructo__UserI__32E0915F");

                    b.Navigation("Expertise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingSystem.API.Models.InstructorProfile", b =>
                {
                    b.HasOne("TrainingSystem.API.Models.User", "User")
                        .WithOne("InstructorProfile")
                        .HasForeignKey("TrainingSystem.API.Models.InstructorProfile", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Instructo__UserI__2A4B4B5E");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingSystem.API.Models.Notification", b =>
                {
                    b.HasOne("TrainingSystem.API.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__UserI__6A30C649");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingSystem.API.Models.Payment", b =>
                {
                    b.HasOne("TrainingSystem.API.Models.Enrollment", "Enrollment")
                        .WithMany("Payments")
                        .HasForeignKey("EnrollmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Payment__Enrollm__6D0D32F4");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("TrainingSystem.API.Models.RoomEquipment", b =>
                {
                    b.HasOne("TrainingSystem.API.Models.Equipment", "Equipment")
                        .WithMany("RoomEquipments")
                        .HasForeignKey("EquipmentId")
                        .IsRequired()
                        .HasConstraintName("FK__RoomEquip__Equip__3A81B327");

                    b.HasOne("TrainingSystem.API.Models.Room", "Room")
                        .WithMany("RoomEquipments")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("FK__RoomEquip__RoomI__398D8EEE");

                    b.Navigation("Equipment");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TrainingSystem.API.Models.TraineeCertificationProgress", b =>
                {
                    b.HasOne("TrainingSystem.API.Models.CertificationTrack", "CertificationTrack")
                        .WithMany("TraineeCertificationProgresses")
                        .HasForeignKey("CertificationTrackId")
                        .IsRequired()
                        .HasConstraintName("FK__TraineeCe__Certi__59063A47");

                    b.HasOne("TrainingSystem.API.Models.User", "User")
                        .WithMany("TraineeCertificationProgresses")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__TraineeCe__UserI__5812160E");

                    b.Navigation("CertificationTrack");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingSystem.API.Models.User", b =>
                {
                    b.HasOne("TrainingSystem.API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__User__RoleId__276EDEB3");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TrainingSystem.API.Models.CertificationTrack", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("CertificationTrackCourses");

                    b.Navigation("TraineeCertificationProgresses");
                });

            modelBuilder.Entity("TrainingSystem.API.Models.Course", b =>
                {
                    b.Navigation("CertificationTrackCourses");

                    b.Navigation("CourseEquipmentRequirements");

                    b.Navigation("CourseSessions");

                    b.Navigation("InversePrerequisiteCourse");
                });

            modelBuilder.Entity("TrainingSystem.API.Models.CourseSession", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("TrainingSystem.API.Models.Enrollment", b =>
                {
                    b.Navigation("AssessmentResults");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("TrainingSystem.API.Models.Equipment", b =>
                {
                    b.Navigation("CourseEquipmentRequirements");

                    b.Navigation("RoomEquipments");
                });

            modelBuilder.Entity("TrainingSystem.API.Models.ExpertiseArea", b =>
                {
                    b.Navigation("InstructorExpertises");
                });

            modelBuilder.Entity("TrainingSystem.API.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TrainingSystem.API.Models.Room", b =>
                {
                    b.Navigation("CourseSessions");

                    b.Navigation("RoomEquipments");
                });

            modelBuilder.Entity("TrainingSystem.API.Models.SubjectCategory", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("TrainingSystem.API.Models.User", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("CourseSessions");

                    b.Navigation("Enrollments");

                    b.Navigation("InstructorAvailabilities");

                    b.Navigation("InstructorExpertises");

                    b.Navigation("InstructorProfile");

                    b.Navigation("Notifications");

                    b.Navigation("TraineeCertificationProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
